version: '3.7'

services:
  nginx:
    image: nginx:nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always

  mariadb:
    image: mariadb:mariadb
    build: ./requirements/mariadb
    env_file: 
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
  
    restart: always

  wordpress:
    image: wordpress:wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always


volumes:
  wordpress:
    driver_opts:
      type: none
      o: bind
      device: /home/yoibarki/data/wordpress
  mariadb:
    driver_opts:
      type: none
      o: bind
      device: /home/yoibarki/data/mariadb

networks:
  inception:
     