version: '3.7'

services:
  nginx:
    image: nginx:latest
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always

  mariadb:
    image: mariadb:latest
    build: ./requirements/mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    image: wordpress:latest
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/yoibarki/data/wordpress

  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/yoibarki/data/mariadb

networks:
  inception: