services:
  nginx:
    image: nginx:latest
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
      # - frontend
      # - backend
    restart: always
    

  mariadb:
    image: mariadb:10.5.23
    build: ./requirements/mariadb
    # environment:
    #   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #   MYSQL_DATABASE: ${MYSQL_DATABASE}
    #   MYSQL_USER: ${MYSQL_USER}
    #   MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
      # - backend
    restart: always


  wordpress:
    image: wordpress:latest
    ports: 
      - "9000:443"
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    # environment:
    #   WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
    #   WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
    #   WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    #   WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
      # - backend
    restart: always
  
volumes:
  # mariadb:
  #   name: mariadb
  #   driver: local
  #   driver_opts:
  #     device: /home/data/mariadb
  #     o: bind
  #     type: none
  # wordpress:
  #   name: wordpress
  #   driver: local
  #   driver_opts:
  #     device: /home/data/wordpress
  #     o: bind
  #     type: none
  wordpress:
  mariadb:

networks:
  inception:
    name: inception
  # frontend:
  # backend:
